function cellInfo = bus_QuadRotorParameters(varargin) 
% BUS_QUADROTORPARAMETERS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the m-file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'QuadRotorParameters', ... 
    '', ... 
    sprintf(''), { ... 
      {'mass', 1, 'double', -1, 'real', 'Sample'}; ...
      {'Inb', [3 3], 'double', -1, 'real', 'Sample'}; ...
      {'len', 1, 'double', -1, 'real', 'Sample'}; ...
      {'R', 1, 'double', -1, 'real', 'Sample'}; ...
      {'c', 1, 'double', -1, 'real', 'Sample'}; ...
      {'b', 1, 'double', -1, 'real', 'Sample'}; ...
      {'theta_R', 1, 'double', -1, 'real', 'Sample'}; ...
      {'theta_T', 1, 'double', -1, 'real', 'Sample'}; ...
      {'a0', 1, 'double', -1, 'real', 'Sample'}; ...
      {'Cd', 1, 'double', -1, 'real', 'Sample'}; ...
      {'rho', 1, 'double', -1, 'real', 'Sample'}; ...
      {'g', 1, 'double', -1, 'real', 'Sample'}; ...
      {'tau', 1, 'double', -1, 'real', 'Sample'}; ...
      {'Kcmd', 1, 'double', -1, 'real', 'Sample'}; ...
      {'cmd_st', 1, 'double', -1, 'real', 'Sample'}; ...
      {'beta', 1, 'double', -1, 'real', 'Sample'}; ...
      {'v0', 1, 'double', -1, 'real', 'Sample'}; ...
      {'alpha', 1, 'double', -1, 'real', 'Sample'}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
