function cellInfo = bus_FuselageParameters(varargin) 
% BUS_FUSELAGEPARAMETERS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the m-file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'FuselageParameters', ... 
    '', ... 
    sprintf(''), { ... 
      {'carea', 1, 'double', -1, 'real', 'Sample'}; ...
      {'clen', 1, 'double', -1, 'real', 'Sample'}; ...
      {'cx', 3, 'double', -1, 'real', 'Sample'}; ...
      {'cy', 3, 'double', -1, 'real', 'Sample'}; ...
      {'cz', 3, 'double', -1, 'real', 'Sample'}; ...
      {'cm', 3, 'double', -1, 'real', 'Sample'}; ...
      {'cn', 3, 'double', -1, 'real', 'Sample'}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
