function cellInfo = bus_FinParameters(varargin) 
% BUS_FINPARAMETERS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the m-file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'FinParameters', ... 
    '', ... 
    sprintf(''), { ... 
      {'span', 1, 'double', -1, 'real', 'Sample'}; ...
      {'chord', 1, 'double', -1, 'real', 'Sample'}; ...
      {'dihedral', 1, 'double', -1, 'real', 'Sample'}; ...
      {'incid', 1, 'double', -1, 'real', 'Sample'}; ...
      {'sweep', 1, 'double', -1, 'real', 'Sample'}; ...
      {'taper', 1, 'double', -1, 'real', 'Sample'}; ...
      {'stall', 1, 'double', -1, 'real', 'Sample'}; ...
      {'a0', 1, 'double', -1, 'real', 'Sample'}; ...
      {'a1s2', 1, 'double', -1, 'real', 'Sample'}; ...
      {'cd0', 1, 'double', -1, 'real', 'Sample'}; ...
      {'cd1s1', 1, 'double', -1, 'real', 'Sample'}; ...
      {'cd2c1', 1, 'double', -1, 'real', 'Sample'}; ...
      {'cm0', 1, 'double', -1, 'real', 'Sample'}; ...
      {'cm1s1', 1, 'double', -1, 'real', 'Sample'}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
